apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: APP_NAME-config
  namespace: heezy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: APP_NAME-data
  namespace: heezy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 100Gi
